name: Prepare repo
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v2
      with:
        cache: yarn
        registry-url: 'https://registry.npmjs.org'
        node-version-file: '.nvmrc'

    - uses: actions/cache@v2
      id: yarn-cache
      name: Restore yarn cache
      with:
        path: ${{ steps.yarn-cache-get-dir.outputs.dir }}
        key: ${{ runner.os }}-yarn-v1-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-v1-

    - uses: actions/cache@v2
      name: Restore loom Cache
      with:
        path: .loom
        key: ${{ runner.os }}-loom-v1-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-loom-v1-

    - name: Install dependencies
      run: yarn install
      shell: bash
