name: Changesets reminder

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - opened
      - synchronize
      - reopened
    paths:
      ['packages/*/src/**', 'packages/*/package.json', '!*.test.*', '!*.md']

jobs:
  check:
    if: |
      !contains(github.event.pull_request.head.ref, 'changeset-release')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: mskelton/changelog-reminder-action@v2
        with:
          changelogRegex: "\\.changeset"
          message: >
            We detected some changes in `packages/*/package.json` or `packages/*/src`, and there are no updates in the `.changeset` directory.
            If the changes are user-facing and should cause a version bump, run `yarn changeset` to track your changes and include them in the next release CHANGELOG.
            If you are making simple updates to repo configuration, examples, or documentation, you do not need to add a changeset.
